/**
 * Unit Display Names Helper
 * 
 * Provides functions to get human-readable names for units
 * using the synced manifest from Comlink.
 */

// Import the manifest (this will be generated by comlink-asset-sync.js)
let unitsManifest: UnitsManifest | null = null;

interface UnitInfo {
  name: string;
  type: 'CHARACTER' | 'SHIP';
  alignment: string;
  thumbnailName?: string;
  categories?: string[];
}

interface UnitsManifest {
  version: string;
  generated: string;
  units: Record<string, UnitInfo>;
}

/**
 * Load the units manifest (lazy loaded)
 */
async function loadManifest(): Promise<UnitsManifest> {
  if (unitsManifest) return unitsManifest;
  
  try {
    // Dynamic import for the manifest
    const data = await import('@/data/units-manifest.json');
    unitsManifest = data.default || data;
    return unitsManifest!;
  } catch (error) {
    console.warn('Units manifest not found, using fallback names');
    return { version: 'unknown', generated: '', units: {} };
  }
}

/**
 * Get display name for a unit (sync version for components)
 * Falls back to formatted gameId if not found
 */
export function getUnitDisplayName(gameId: string, manifest?: UnitsManifest): string {
  if (manifest?.units?.[gameId]?.name) {
    return manifest.units[gameId].name;
  }
  
  // Fallback: format the gameId nicely
  return formatGameId(gameId);
}

/**
 * Format a gameId into a readable name
 * B2SUPERBATTLEDROID → B2 Super Battle Droid
 */
export function formatGameId(gameId: string): string {
  return gameId
    .replace(/_/g, ' ')
    .replace(/([A-Z])([A-Z]+)/g, (_, first, rest) => 
      first + rest.toLowerCase()
    )
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .trim();
}

/**
 * Get unit info including type and alignment
 */
export function getUnitInfo(gameId: string, manifest?: UnitsManifest): UnitInfo | null {
  return manifest?.units?.[gameId] || null;
}

/**
 * Check if a unit is a ship
 */
export function isShip(gameId: string, manifest?: UnitsManifest): boolean {
  return manifest?.units?.[gameId]?.type === 'SHIP';
}

/**
 * Get the portrait image path for a unit
 */
export function getUnitPortraitPath(gameId: string, manifest?: UnitsManifest): string {
  const unitInfo = manifest?.units?.[gameId];
  const isShipUnit = unitInfo?.type === 'SHIP';
  const folder = isShipUnit ? 'ships' : 'characters';
  return `/${folder}/${gameId}.png`;
}

/**
 * Get fallback image path based on unit type
 */
export function getFallbackPortraitPath(gameId: string, manifest?: UnitsManifest): string {
  const isShipUnit = isShip(gameId, manifest);
  return isShipUnit ? '/fallback/ship-portrait.svg' : '/fallback/character-portrait.svg';
}

/**
 * Server-side helper to load manifest synchronously
 * Use this in getServerSideProps or API routes
 */
export async function getUnitsManifest(): Promise<UnitsManifest> {
  return loadManifest();
}

/**
 * Pre-loaded manifest for client components
 * Export this after running the sync script
 */
export { unitsManifest };
